FOSWIKI_ROOT?=~/foswiki/trunk/core
TARGET=da.js sv.js

-include $(FOSWIKI_ROOT)/pub/System/JQueryPlugin/Makefile.include

from-git:
	cp ../git/src/javascript/i18n/*js .

to-git:
	cp *js ../git/src/javascript/i18n/
